# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68e8b1e41886d8fff17e12b1890ad820153e2a7ee3a350fbc7b338a753cdb4fb6ce90c8a9c071dfc07950d9b99fa143fe687ac1a9028c2a328ab8e9d754c8435

test:
  secret_key_base: 4b29dc9bba59cbfaa62fab88c6464406f730e475358f2bbbd55b80a06e486c604aa4c0b7784cb4374366fd06029d1983160705101e87e3bd773eaa80cd51d385

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
